"""
Candidate profile + internship eligibility — SS2.

Owned by the SS2 implementer. Do not edit this file from SS1/SS3 work.
Integration points for other subsystems:
  - SS3 browse query joins CandidateProfile with CandidateEligibility.
  - SS1 writes CandidateEligibility(source='spoc_approved', cohort_id=...)
    via the SPOC greenlight endpoint (cohorts.py); see spec.
  - certificate_service.issue_certificate() appends
    CandidateEligibility(source='auto_certificate', eligible=True).
"""
from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Boolean, Date, ForeignKey, JSON, UniqueConstraint, Index
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base


class CandidateProfile(Base):
    """
    Candidate profile for the internship marketplace.

    Visible to approved Companies (SS3) only when is_visible=True AND
    the candidate has an eligible CandidateEligibility row.
    """
    __tablename__ = "candidate_profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=True, index=True)

    is_visible = Column(Boolean, default=False, nullable=False)

    # Resume file (PDF) uploaded via /api/v1/uploads/document
    resume_url = Column(String(500), default="")

    bio = Column(Text, default="")

    # JSON list[str]
    skills = Column(JSON, default=list)
    preferred_roles = Column(JSON, default=list)

    availability_date = Column(Date, nullable=True)

    linkedin_url = Column(String(500), default="")
    github_url = Column(String(500), default="")
    portfolio_url = Column(String(500), default="")

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", foreign_keys=[user_id])

    def __repr__(self):
        return f"<CandidateProfile(user_id={self.user_id}, is_visible={self.is_visible})>"


class CandidateEligibility(Base):
    """
    Per-user internship eligibility record.

    source:
      - 'auto_certificate'  (organic student earned a certificate)
      - 'spoc_approved'     (SPOC greenlight for a cohort student)

    A user may end up with multiple rows over time (e.g. multi-source), but
    the uniqueness is enforced on (user_id) so re-issuing the same kind of
    decision updates the existing row. Callers MUST upsert.
    """
    __tablename__ = "candidate_eligibility"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=True, index=True)

    source = Column(String(32), nullable=False)  # auto_certificate | spoc_approved
    eligible = Column(Boolean, default=True, nullable=False)
    reason = Column(Text, default="")

    decided_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    decided_at = Column(DateTime(timezone=True), server_default=func.now())

    # Optional link to a cohort (only set when source='spoc_approved')
    # Uses string FK to avoid a hard import-order dependency on models.cohort
    # (SS1 module may or may not be loaded yet in tests).
    cohort_id = Column(Integer, ForeignKey("cohorts.id", use_alter=True, name="fk_eligibility_cohort"), nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("ix_candidate_eligibility_source_eligible", "source", "eligible"),
    )

    user = relationship("User", foreign_keys=[user_id])
    decider = relationship("User", foreign_keys=[decided_by])

    def __repr__(self):
        return f"<CandidateEligibility(user_id={self.user_id}, source={self.source}, eligible={self.eligible})>"
