import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { growthAPI, type GrowthContract } from '@/api/growth';
import { plannerError } from '@/api/planner';
import api from '@/api/axios';

const button = 'rounded-xl border border-orange-200 bg-orange-50 px-4 py-2 text-sm font-semibold text-orange-800 disabled:opacity-50';
interface Delivery { id: number; resource_type: string; resource_reference: string; status: string; access_active: boolean; valid_until: string | null; asset_url: string | null }
interface Offer { id: number; tenant_id: number; payload: { recommendations: { offer_id: number; kind: string; reason: string; discount_bps: number }[] } }
export function GrowthCustomerLifecycle() {
  const [contracts, setContracts] = useState<GrowthContract[]>([]); const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [offers, setOffers] = useState<Offer[]>([]);
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [cancel, setCancel] = useState<number | null>(null);
  const load = useCallback(async () => { const [billing, recommendations] = await Promise.all([growthAPI.get<{ contracts: GrowthContract[]; deliveries: Delivery[] }>('/my-billing'), growthAPI.get<Offer[]>('/my-offers')]); setContracts(billing.contracts); setDeliveries(billing.deliveries); setOffers(recommendations); }, []);
  useEffect(() => { load().catch(e => setError(plannerError(e))); }, [load]);
  const run = async (fn: () => Promise<unknown>, notice: string) => { setBusy(true); setError(''); try { await fn(); await load(); setMessage(notice); } catch (e) { setError(plannerError(e)); } finally { setBusy(false); } };
  const download = async (d: Delivery) => {
    if (!d.asset_url) return;
    const response = await api.get(d.asset_url.replace('/api/v1', ''), { responseType: 'blob' });
    const url = URL.createObjectURL(response.data); const a = document.createElement('a'); a.href = url; a.download = `SashaInfinity-model-${d.resource_reference}.glb`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="space-y-4">
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{message && <p role="status" className="rounded-xl bg-orange-50 p-4">{message}</p>}
    <section className="rounded-2xl border border-orange-100 bg-white p-6"><h2 className="mb-4 text-xl font-bold">Purchased services & access</h2>{deliveries.length === 0 && <p className="text-sm text-slate-500">Paid purchases appear here with their fulfillment status.</p>}{deliveries.map(d => <div key={d.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3 text-sm"><span>{d.resource_type.replace(/_/g, ' ')} · {d.status}<small className="block text-slate-500">{d.access_active ? 'Access active' : 'Not currently active'} · {d.valid_until ? `Through ${d.valid_until} (exclusive)` : 'No scheduled expiry'}</small></span>{d.asset_url && <button className={button} disabled={busy} onClick={() => run(() => download(d), 'Licensed asset downloaded')}>Download licensed asset</button>}{d.access_active && d.resource_type === 'institution_saas' && <Link className={button} to="/institutions">Open institution</Link>}</div>)}</section>
    <section className="rounded-2xl border border-orange-100 bg-white p-6"><h2 className="mb-4 text-xl font-bold">Recurring agreements</h2>{contracts.filter(c => c.billing_interval).map(c => <div key={c.id} className="border-t py-3 text-sm"><div className="flex items-center justify-between gap-3"><span>Agreement #{c.id} · {c.status} · {c.billing_interval}<small className="block">Next invoice: {c.next_billing_on || 'Not scheduled'}</small></span>{c.status === 'active' && <button className={button} disabled={busy} onClick={() => setCancel(c.id)}>Cancel renewal</button>}</div>{cancel === c.id && <form className="mt-3 grid gap-3 rounded-xl bg-orange-50 p-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(async () => { await growthAPI.post(`/contracts/${c.id}/cancel-renewal`, { reason: String(f.get('reason')) }); setCancel(null); }, 'Renewal cancelled. Paid access remains through its purchased period.'); }}><p>Future automatic invoices stop. Existing invoices remain payable; this does not request a refund.</p><input name="reason" aria-label="Cancellation reason" required minLength={5} maxLength={500} className="rounded-xl border p-2" placeholder="Reason for cancellation" /><label><input type="checkbox" required className="mr-2" />I understand the effect of cancelling renewal.</label><div className="flex gap-2"><button className={button} disabled={busy}>Confirm cancellation</button><button type="button" className={button} onClick={() => setCancel(null)}>Keep agreement</button></div></form>}</div>)}</section>
    <section className="rounded-2xl border border-orange-100 bg-white p-6"><h2 className="mb-2 text-xl font-bold">Reviewed offers for your workspace</h2><p className="mb-4 text-sm text-slate-500">Offers expire 30 days after creation. Acceptance creates an agreement, not a charge. Subscription offers bill monthly. <Link className="text-orange-700 underline" to="/communication-preferences">Manage optional offer notifications</Link>.</p>{offers.length === 0 && <p className="text-sm">No active reviewed offers.</p>}{offers.map(o => <div key={o.id}>{o.payload.recommendations.map((p, i) => <article key={i} className="mt-3 rounded-xl border border-orange-100 p-4"><h3 className="font-semibold">Workspace #{o.tenant_id} · Offer #{p.offer_id} · {p.discount_bps / 100}% reviewed discount</h3><p className="my-3 text-sm">{p.reason}</p><button className={button} disabled={busy} onClick={() => run(() => growthAPI.post(`/recommendations/${o.id}/accept/${i}`), 'Offer accepted. The team will issue a reviewed tax invoice before payment.')}>Accept reviewed offer</button></article>)}</div>)}</section>
  </div>;
}
