-- add_lx_model_columns.sql — 2026-09-03
--
-- Comprehensive model-vs-DB audit after the learning-experience wave:
-- create_all never adds columns to existing tables, so every new model
-- column on a pre-existing table was missing (course detail 500'd on
-- assignments.late_policy first). Generated by comparing every
-- backend/app/models Column() against information_schema.

ALTER TABLE assignments ADD COLUMN IF NOT EXISTS late_policy VARCHAR(255);
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS late_penalty_pct INTEGER;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS rubric TEXT;
ALTER TABLE assignment_submissions ADD COLUMN IF NOT EXISTS is_late BOOLEAN;
ALTER TABLE assignment_submissions ADD COLUMN IF NOT EXISTS rubric_scores TEXT;
ALTER TABLE certificates ADD COLUMN IF NOT EXISTS is_global BOOLEAN;
