import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, BarChart3, Briefcase, FlaskConical, ShieldCheck, Sparkles, Wallet } from 'lucide-react';
import { growthAPI, type GrowthLead, type GrowthOffer, type GrowthSnapshot } from '@/api/growth';
import { plannerError } from '@/api/planner';
import { GrowthExecutionPanel } from './GrowthExecutionPanel';

const field = 'w-full rounded-xl border border-orange-100 bg-white px-3 py-2 text-sm text-slate-900';
const secondary = 'rounded-xl border border-orange-200 bg-white px-4 py-2 text-sm font-semibold text-orange-800 disabled:opacity-50';
const primary = 'rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 px-4 py-2 text-sm font-semibold text-white shadow-sm disabled:opacity-50';
const money = (n: number | null) => n == null ? 'Not enough data' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border border-orange-100 bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-semibold text-slate-900">{title}</h3>{children}</section>; }
function Input({ name, label, type = 'text', value, required = true }: { name: string; label: string; type?: string; value?: string | number; required?: boolean }) { return <label className="grid gap-1 text-xs font-medium text-slate-600">{label}<input className={field} name={name} type={type} defaultValue={value} required={required} /></label>; }
function Select({ name, label, options, value }: { name: string; label: string; options: string[]; value?: string }) { return <label className="grid gap-1 text-xs font-medium text-slate-600">{label}<select className={field} name={name} defaultValue={value}>{options.map(o => <option key={o}>{o}</option>)}</select></label>; }
const data = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); return Object.fromEntries(new FormData(e.currentTarget)) as Record<string, string>; };
const num = (v: string) => v ? Number(v) : null;

export function GrowthControlPlane() {
  const [snapshot, setSnapshot] = useState<GrowthSnapshot | null>(null);
  const [offers, setOffers] = useState<GrowthOffer[]>([]);
  const [tab, setTab] = useState('overview'); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [lead, setLead] = useState<GrowthLead | null>(null);
  const [results, setResults] = useState<{ decision: string; results: { key: string; subjects: number; converted: number }[] } | null>(null);
  const refresh = useCallback(async () => { const [s, o] = await Promise.all([growthAPI.snapshot(), growthAPI.offers()]); setSnapshot(s); setOffers(o); }, []);
  useEffect(() => { refresh().catch(e => setError(plannerError(e))); }, [refresh]);
  const run = async (fn: () => Promise<unknown>, message = 'Saved successfully') => {
    setBusy(true); setError(''); setNotice('');
    try { await fn(); await refresh(); setNotice(message); } catch (e) { setError(plannerError(e)); } finally { setBusy(false); }
  };
  const offerSelect = <label className="grid gap-1 text-xs font-medium text-slate-600">Offer<select className={field} name="offer_id" required>{offers.map(o => <option key={o.id} value={o.id}>{o.name} · {o.business_vertical}</option>)}</select></label>;
  const tabs = [{ id: 'overview', label: 'Revenue intelligence', Icon: BarChart3 }, { id: 'billing', label: 'Billing & delivery', Icon: Wallet }, { id: 'crm', label: 'Sales pipeline', Icon: Briefcase }, { id: 'experiments', label: 'Experiments', Icon: FlaskConical }, { id: 'ai', label: 'AI opportunities', Icon: Sparkles }, { id: 'validation', label: 'Launch evidence', Icon: ShieldCheck }];
  return <div className="space-y-5">
    <header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-orange-600 via-orange-500 to-amber-400 p-7 text-white">
      <p className="text-xs font-semibold uppercase tracking-[.25em] text-orange-100">SashaInfinity • Growth OS</p>
      <h2 className="mt-3 text-3xl font-bold">Three pillars. One revenue engine.</h2>
      <p className="mt-3 max-w-2xl text-sm text-orange-50">Turn customer intent into accountable revenue—with reviewed pricing, traceable delivery and one financial ledger.</p>
      <div className="mt-5 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 rounded-xl bg-white/20 px-4 py-2 text-sm font-semibold" to="/business-services">Customer storefront <ArrowUpRight size={16} /></Link><button className="rounded-xl bg-white/20 px-4 py-2 text-sm" disabled={busy} onClick={() => run(() => growthAPI.post('/maintenance'), 'Billing schedules and follow-ups processed')}>Process due workflows</button></div>
    </header>
    <nav aria-label="Growth modules" className="flex flex-wrap gap-2">{tabs.map(({ id, label, Icon }) => <button key={id} onClick={() => setTab(id)} aria-pressed={tab === id} className={(tab === id ? primary : secondary) + ' flex items-center gap-2'}><Icon size={16} />{label}</button>)}</nav>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-orange-50 p-4 text-orange-900">{notice}</p>}
    {!snapshot ? <p>Loading revenue operations…</p> : <>
      {tab === 'overview' && <>
        <GrowthExecutionPanel />
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Net commercial revenue', money(snapshot.analytics.net_revenue)], ['Acquisition cost / customer', money(snapshot.analytics.cac)], ['Realized lifetime value', money(snapshot.analytics.realized_ltv)], ['Monthly run-rate estimate', money(snapshot.analytics.forecast.monthly_run_rate)]].map(([label, value]) => <Card key={label} title={label}><p className="text-2xl font-bold text-orange-600">{value}</p></Card>)}</div>
        <p className="text-sm text-slate-600">90-day window. {snapshot.analytics.scope}. CAC uses recorded marketing spend; missing spend can understate it. LTV is realized net revenue, not a future prediction.</p>
        <div className="grid gap-4 lg:grid-cols-2"><Card title="Sales outlook"><p className="text-2xl font-bold">{money(snapshot.analytics.forecast.weighted_open_pipeline)}</p><p className="mt-2 text-sm text-slate-600">Probability-weighted open pipeline. {snapshot.analytics.forecast.method}.</p></Card><Card title="Retention watch"><p className="mb-3 text-xs text-slate-500">{snapshot.analytics.risk_method}</p>{snapshot.analytics.risks.length === 0 && <p>No billing-risk flags in the checked agreements.</p>}{snapshot.analytics.risks.map(r => <p key={r.contract_id} className="border-t py-2 text-sm">Workspace #{r.tenant_id} · score {r.score}/100 · {r.reasons.join(', ')}</p>)}</Card></div>
        <Card title="Customer cohorts"><p className="mb-3 text-sm text-slate-500">Repeat payment activity is not product engagement or a churn-rate estimate.</p>{snapshot.analytics.cohorts.map(c => <p key={c.month} className="border-t py-2">{c.month} · {c.customers} acquired · {c.repeat_paid_last_30d} repeat payers in last 30 days</p>)}</Card>
        <Card title="Record campaign spend"><form className="grid gap-3 md:grid-cols-3" onSubmit={e => { const f = data(e); run(() => growthAPI.post('/spend', { ...f, amount: Number(f.amount), currency: 'INR' })); }}><Input name="source_key" label="Unique import/reference key" /><Input name="source" label="Source (e.g. Google)" /><Input name="campaign" label="Campaign" required={false} /><Select name="business_vertical" label="Pillar" options={['meiporul', 'seyappaduporul', 'utporul']} /><Input name="incurred_on" label="Spend date" type="date" /><Input name="amount" label="Spend in INR" type="number" /><button className={primary} disabled={busy}>Record spend</button></form></Card>
      </>}
      {tab === 'billing' && <>
        <p className="text-sm text-slate-600">Create offers and contracts in <Link className="text-orange-700 underline" to="/admin/operations?view=commercial">Commercial</Link>, then configure reviewed tax and fulfillment below. Automatic billing issues invoices; it does not auto-debit customers.</p>
        <Card title="Tax & fulfillment policy"><form className="grid gap-3 md:grid-cols-3" onSubmit={e => { const f = data(e); const tax_profile = { supplier_name: f.supplier_name, supplier_address: f.supplier_address, supplier_gstin: f.supplier_gstin, supplier_state: f.supplier_state, customer_name: f.customer_name, customer_address: f.customer_address, customer_gstin: f.customer_gstin, place_of_supply: f.place_of_supply, hsn_sac: f.hsn_sac, rate_bps: Number(f.rate_bps), exemption_reason: f.exemption_reason, reviewed_by: f.reviewed_by, reverse_charge: f.reverse_charge === 'yes' }; run(() => growthAPI.put(`/contracts/${f.contract_id}/policy`, { tax_profile, resource_type: f.resource_type, resource_reference: f.resource_reference, recipient_id: num(f.recipient_id), partner_id: num(f.partner_id), partner_bps: Number(f.partner_bps), payment_terms_days: Number(f.payment_terms_days), automation_enabled: f.automation_enabled === 'yes' })); }}>
          <label className="grid gap-1 text-xs">Contract<select name="contract_id" className={field} required>{snapshot.contracts.filter(c => c.status === 'active').map(c => <option key={c.id} value={c.id}>#{c.id} · Workspace {c.tenant_id} · Offer {c.offer_id}</option>)}</select></label>
          <Select name="resource_type" label="Delivery type" options={['asset_license', 'lab_deployment', 'amc', 'device_service', 'institution_saas', 'franchise', 'managed_service', 'premium_credential', 'career_service', 'creator_commerce']} /><Input name="resource_reference" label="Asset / agreement / course reference" />
          <Input name="supplier_name" label="Supplier legal name" /><Input name="supplier_address" label="Supplier address" /><Input name="supplier_gstin" label="Supplier GSTIN" required={false} /><Input name="supplier_state" label="Supplier state code" /><Input name="customer_name" label="Customer legal name" /><Input name="customer_address" label="Customer address" /><Input name="customer_gstin" label="Customer GSTIN" required={false} /><Input name="place_of_supply" label="Place of supply state code" /><Input name="hsn_sac" label="Reviewed HSN / SAC" /><Input name="rate_bps" label="Tax basis points (1800 = 18%)" type="number" /><Input name="exemption_reason" label="Exemption basis (required if zero tax)" required={false} /><Input name="reviewed_by" label="Tax reviewer / approval reference" /><Select name="reverse_charge" label="Reverse charge" options={['no', 'yes']} /><Input name="recipient_id" label="Recipient user ID (credentials)" type="number" required={false} /><Input name="partner_id" label="Revenue-share partner user ID" type="number" required={false} /><Input name="partner_bps" label="Partner basis points (2000 = 20%)" type="number" value={0} /><Input name="payment_terms_days" label="Payment terms in days" type="number" value={14} /><Select name="automation_enabled" label="Issue recurring invoices automatically" options={['no', 'yes']} /><button disabled={busy} className={primary}>Save reviewed policy</button>
        </form></Card>
        <Card title="Issue invoice"><form className="grid gap-3 md:grid-cols-4" onSubmit={e => { const f = data(e); run(() => growthAPI.post(`/contracts/${f.contract_id}/issue`, { period_key: f.period_key, milestone_bps: Number(f.milestone_bps) })); }}><Input name="contract_id" label="Contract ID" type="number" /><Input name="period_key" label="Unique milestone key or cycle:YYYY-MM-DD" /><Input name="milestone_bps" label="Milestone share (10000 = full)" type="number" value={10000} /><button disabled={busy} className={primary}>Issue invoice</button></form><div className="mt-4 space-y-2">{snapshot.invoices.map(i => <div key={i.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-orange-50/60 p-3 text-sm"><span>{i.invoice_number} · {i.currency} {i.total_amount} · {i.status}</span><div className="flex gap-2"><button className={secondary} onClick={() => run(() => growthAPI.invoice(i.id), 'Invoice downloaded')}>PDF</button><button className={secondary} disabled={busy} onClick={() => run(() => growthAPI.post(`/invoices/${i.id}/reconcile`), 'Payment status refreshed')}>Reconcile</button></div></div>)}</div></Card>
        <Card title="Service delivery"><form className="grid gap-3 md:grid-cols-3" onSubmit={e => { const f = data(e); run(() => growthAPI.post(`/deliveries/${f.delivery_id}/complete`, { evidence: f.evidence })); }}><label className="grid gap-1 text-xs">Paid delivery<select className={field} name="delivery_id" required>{snapshot.deliveries.filter(d => d.status === 'pending').map(d => <option key={d.id} value={d.id}>#{d.id} · {d.resource_type} · Workspace {d.tenant_id}</option>)}</select></label><Input name="evidence" label="Delivery evidence / acceptance reference" /><button className={primary} disabled={busy}>Confirm fulfillment</button></form><p className="mt-3 text-xs text-slate-500">Payment alone does not certify learning or prove physical deployment. Record verified delivery evidence.</p></Card>
        <Card title="Creator & partner earnings">{snapshot.partner_balances.map(b => <p key={`${b.partner_id}-${b.currency}`} className="mb-2">Partner #{b.partner_id} · {b.currency} {b.available} available · {b.unsettled} unsettled</p>)}<form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={e => { const f = data(e); run(() => growthAPI.post('/settlements', { partner_id: Number(f.partner_id), expected_amount: Number(f.expected_amount), reference: f.reference, currency: 'INR' }), 'External payout recorded; no bank transfer was initiated'); }}><Input name="partner_id" label="Partner user ID" type="number" /><Input name="expected_amount" label="Entire available balance INR" type="number" /><Input name="reference" label="Verified bank payout reference" /><button className={primary} disabled={busy}>Record external payout</button></form><p className="mt-3 text-xs text-slate-500">14-day hold; refunds create clawbacks. This records a completed external payout, not a money-transfer instruction.</p></Card>
      </>}
      {tab === 'crm' && <div className="grid gap-4 lg:grid-cols-2"><Card title="Lead inbox">{snapshot.leads.length === 0 && <p>No leads yet. Process due workflows to import the existing campus inbox.</p>}{snapshot.leads.map(l => <button key={l.id} className="mb-2 flex w-full justify-between rounded-xl border border-orange-100 p-3 text-left text-sm" onClick={() => setLead(l)}><span className="font-medium">{l.company || l.name}<small className="block text-slate-500">{l.business_vertical} · {l.stage}</small></span><span className="text-orange-700">{l.score}/100</span></button>)}</Card><Card title="Qualification & follow-up">{lead ? <form key={`${lead.id}-${lead.version}`} className="grid gap-3" onSubmit={e => { const f = data(e); run(async () => { await growthAPI.put(`/leads/${lead.id}`, { version: lead.version, stage: f.stage, owner_id: num(f.owner_id), next_follow_up: f.next_follow_up || null, contract_id: num(f.contract_id), budget_confirmed: f.budget_confirmed === 'on', decision_maker: f.decision_maker === 'on', demo_attended: f.demo_attended === 'on' }); setLead(null); }); }}><p>{lead.name} · {lead.email}</p><Select name="stage" label="Stage" options={['new', 'contacted', 'qualified', 'proposal', 'won', 'lost']} value={lead.stage} /><Input name="owner_id" label="Sales admin user ID" type="number" value={lead.owner_id || ''} required={false} /><Input name="contract_id" label="Linked customer contract ID" type="number" value={lead.contract_id || ''} required={false} /><Input name="next_follow_up" label="Next follow-up" type="date" value={lead.next_follow_up || ''} required={false} />{['budget_confirmed', 'decision_maker', 'demo_attended'].map(k => <label key={k} className="text-sm"><input type="checkbox" name={k} defaultChecked={lead.signals[k]} className="mr-2 accent-orange-500" />{k.replace(/_/g, ' ')}</label>)}<p className="text-xs text-slate-500">Budget 30 + decision-maker 30 + attended demo 40. Won requires a paid linked invoice.</p><button className={primary} disabled={busy}>Save lead</button></form> : <p>Select a lead to review.</p>}<h4 className="mb-2 mt-6 font-semibold">Open tasks</h4>{snapshot.tasks.filter(t => t.status === 'open').map(t => <div key={t.id} className="flex items-center justify-between gap-2 border-t py-3 text-sm"><span>{t.title}<small className="block">Due {t.due_on}</small></span><button className={secondary} disabled={busy} onClick={() => run(() => growthAPI.post(`/tasks/${t.id}/complete`))}>Done</button></div>)}</Card></div>}
      {tab === 'experiments' && <>
        <Card title="Create controlled experiment"><form className="grid gap-3 md:grid-cols-3" onSubmit={e => { const f = data(e); run(() => growthAPI.post('/experiments', { name: f.name, kind: f.kind, offer_id: Number(f.offer_id), minimum_sample: Number(f.minimum_sample), variants: [{ key: 'control', headline: f.control_headline, message: f.control_message, discount_bps: 0 }, { key: 'variant', headline: f.variant_headline, message: f.variant_message, discount_bps: Number(f.discount_bps) }] })); }}><Input name="name" label="Experiment name" />{offerSelect}<Select name="kind" label="Test type" options={['pricing', 'landing', 'campaign']} /><Input name="control_headline" label="Control headline" /><Input name="control_message" label="Control copy" /><Input name="variant_headline" label="Variant headline" /><Input name="variant_message" label="Variant copy" /><Input name="discount_bps" label="Variant discount bps (pricing only, ≤2000)" type="number" value={0} /><Input name="minimum_sample" label="Minimum users per arm" type="number" value={100} /><button className={primary} disabled={busy}>Create draft</button></form></Card>
        <Card title="Experiment register">{snapshot.experiments.map(x => <div key={x.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><span>{x.name}<small className="block text-slate-500">{x.kind} · {x.status}</small></span><div className="flex flex-wrap gap-2">{x.status !== 'completed' && ['running', 'paused', 'completed'].filter(s => s !== x.status).map(s => <button className={secondary} key={s} disabled={busy} onClick={() => run(() => growthAPI.post(`/experiments/${x.id}/status`, { status: s }))}>{s === 'running' ? 'Start' : s === 'paused' ? 'Pause' : 'Finish'}</button>)}<button className={secondary} disabled={busy} onClick={() => run(async () => setResults(await growthAPI.get(`/experiments/${x.id}/results`)), 'Results refreshed')}>Results</button></div></div>)}{results && <div role="status" className="mt-4 rounded-xl bg-orange-50 p-4"><p className="font-semibold">{results.decision.replace(/_/g, ' ')}</p>{results.results.map(r => <p key={r.key}>{r.key}: {r.converted} paid conversions / {r.subjects} exposed users</p>)}</div>}<p className="mt-4 text-xs text-slate-500">Stable account-level assignment. Prices and conversion attribution are resolved server-side. Results never automatically publish a winner.</p></Card>
      </>}
      {tab === 'ai' && <Card title="Reviewed AI opportunities"><form className="flex flex-wrap items-end gap-3" onSubmit={e => { const f = data(e); run(() => growthAPI.post(`/recommendations/${f.tenant_id}`), 'AI proposals generated for review'); }}><Input name="tenant_id" label="Customer workspace ID" type="number" /><button className={primary} disabled={busy}>Generate proposals</button></form><p className="my-4 text-sm text-slate-500">Uses the existing GLM/Gemini vault. Only offer catalog and owned offer IDs are shared. Approval records a decision; it does not silently change prices or send marketing.</p>{snapshot.recommendations.map(r => <div key={r.id} className="mb-3 rounded-xl border border-orange-100 p-4"><p className="font-semibold">Workspace #{r.tenant_id} · {r.status}</p>{r.payload.recommendations.map((p, i) => <p key={i} className="my-2 text-sm">{p.kind} · Offer #{p.offer_id} · {p.discount_bps / 100}% proposed discount<br />{p.reason}</p>)}<div className="flex gap-2">{['approved', 'rejected'].map(s => <button key={s} className={secondary} disabled={busy} onClick={() => run(() => growthAPI.post(`/recommendations/${r.id}/review?decision=${s}`))}>{s === 'approved' ? 'Approve proposal' : 'Reject'}</button>)}</div></div>)}</Card>}
      {tab === 'validation' && <Card title="Production acceptance evidence"><p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">These are operator-recorded evidence entries, not automated certification. Mock tests do not prove live-provider behavior, tax compliance or large-scale capacity.</p><form className="grid gap-3 md:grid-cols-3" onSubmit={e => { const f = data(e); run(() => growthAPI.post('/validations', f)); }}><Select name="area" label="Validation area" options={['payments', 'ai', 'tax', 'postgres_restore', 'worker_failover', 'load', 'mail', 'whatsapp', 'video', 'coding']} /><Select name="environment" label="Environment" options={['local', 'sandbox', 'staging', 'production']} /><Select name="status" label="Outcome" options={['blocked', 'passed', 'failed']} /><Input name="release_ref" label="Release commit / reference" /><Input name="evidence" label="Report reference and observed result (no secrets)" /><button className={primary} disabled={busy}>Record evidence</button></form>{snapshot.validations.map(v => <div key={v.id} className="mt-4 border-t pt-3 text-sm"><p className="font-semibold">{v.area} · {v.environment} · {v.status}</p><p>{v.evidence}</p><small className="text-slate-500">{v.release_ref} · {new Date(v.recorded_at).toLocaleString()}</small></div>)}</Card>}
    </>}
  </div>;
}
