"""Campus academics, private resources, guardian consent and subscriptions."""
from alembic import op
import sqlalchemy as sa
from app.core.migration_operations import idempotent_create_operations

op = idempotent_create_operations(op)

revision = "0031"
down_revision = "0030"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campus_branding",
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("subtitle", sa.String(length=320), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("institution_id"),
    )
    op.create_table(
        "campus_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("gateway_plan_id", sa.String(length=80), nullable=False),
        sa.Column("gateway_subscription_id", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("paid_through", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checkout_url", sa.String(length=500), nullable=False),
        sa.Column("last_event_at", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gateway_subscription_id"),
    )
    op.create_index(
        op.f("ix_campus_subscriptions_institution_id"),
        "campus_subscriptions",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "campus_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "name", name="uq_campus_term"),
    )
    op.create_index(
        op.f("ix_campus_terms_institution_id"),
        "campus_terms",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "parent_link_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_user_id", sa.Integer(), nullable=False),
        sa.Column("student_user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["parent_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_user_id", "student_user_id", name="uq_parent_link_request"
        ),
    )
    op.create_index(
        op.f("ix_parent_link_requests_parent_user_id"),
        "parent_link_requests",
        ["parent_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parent_link_requests_student_user_id"),
        "parent_link_requests",
        ["student_user_id"],
        unique=False,
    )
    op.create_table(
        "campus_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["institution_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["campus_terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campus_assessments_batch_id"),
        "campus_assessments",
        ["batch_id"],
        unique=False,
    )
    op.create_table(
        "campus_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("recorded_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["institution_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["institution_members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "batch_id", "member_id", "day", name="uq_campus_attendance"
        ),
    )
    op.create_index(
        op.f("ix_campus_attendance_batch_id"),
        "campus_attendance",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campus_attendance_member_id"),
        "campus_attendance",
        ["member_id"],
        unique=False,
    )
    op.create_table(
        "campus_mail_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invite_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=250), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["institution_invites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_id"),
    )
    op.create_table(
        "campus_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("filename", sa.String(length=160), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["institution_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campus_resources_institution_id"),
        "campus_resources",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "campus_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("feedback", sa.String(length=1000), nullable=False),
        sa.Column("graded_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["campus_assessments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["institution_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id", "member_id", name="uq_campus_score"),
    )
    op.create_index(
        op.f("ix_campus_scores_assessment_id"),
        "campus_scores",
        ["assessment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campus_scores_assessment_id"), table_name="campus_scores")
    op.drop_table("campus_scores")
    op.drop_index(
        op.f("ix_campus_resources_institution_id"), table_name="campus_resources"
    )
    op.drop_table("campus_resources")
    op.drop_table("campus_mail_jobs")
    op.drop_index(
        op.f("ix_campus_attendance_member_id"), table_name="campus_attendance"
    )
    op.drop_index(op.f("ix_campus_attendance_batch_id"), table_name="campus_attendance")
    op.drop_table("campus_attendance")
    op.drop_index(
        op.f("ix_campus_assessments_batch_id"), table_name="campus_assessments"
    )
    op.drop_table("campus_assessments")
    op.drop_index(
        op.f("ix_parent_link_requests_student_user_id"),
        table_name="parent_link_requests",
    )
    op.drop_index(
        op.f("ix_parent_link_requests_parent_user_id"),
        table_name="parent_link_requests",
    )
    op.drop_table("parent_link_requests")
    op.drop_index(op.f("ix_campus_terms_institution_id"), table_name="campus_terms")
    op.drop_table("campus_terms")
    op.drop_index(
        op.f("ix_campus_subscriptions_institution_id"),
        table_name="campus_subscriptions",
    )
    op.drop_table("campus_subscriptions")
    op.drop_table("campus_branding")
    # ### end Alembic commands ###
