"""Isolated campus courses, lessons and learner progress."""
from alembic import op
import sqlalchemy as sa

revision = "0032"
down_revision = "0031"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campus_learning_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["institution_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campus_learning_courses_institution_id"),
        "campus_learning_courses",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "campus_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["campus_learning_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["campus_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "position", name="uq_campus_lesson_position"),
    )
    op.create_index(
        op.f("ix_campus_lessons_course_id"),
        "campus_lessons",
        ["course_id"],
        unique=False,
    )
    op.create_table(
        "campus_lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["campus_lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["institution_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_id", "member_id", name="uq_campus_lesson_progress"),
    )
    op.create_index(
        op.f("ix_campus_lesson_progress_lesson_id"),
        "campus_lesson_progress",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campus_lesson_progress_member_id"),
        "campus_lesson_progress",
        ["member_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_campus_lesson_progress_member_id"), table_name="campus_lesson_progress"
    )
    op.drop_index(
        op.f("ix_campus_lesson_progress_lesson_id"), table_name="campus_lesson_progress"
    )
    op.drop_table("campus_lesson_progress")
    op.drop_index(op.f("ix_campus_lessons_course_id"), table_name="campus_lessons")
    op.drop_table("campus_lessons")
    op.drop_index(
        op.f("ix_campus_learning_courses_institution_id"),
        table_name="campus_learning_courses",
    )
    op.drop_table("campus_learning_courses")
    # ### end Alembic commands ###
