map $http_user_agent $is_crawler {
    default 0;
    ~*twitterbot 1;
    ~*facebookexternalhit 1;
    ~*linkedinbot 1;
    ~*slackbot 1;
    ~*telegrambot 1;
    ~*whatsapp 1;
    ~*googlebot 1;
    ~*bingbot 1;
    ~*slurp 1;
    ~*duckduckbot 1;
    ~*baiduspider 1;
    ~*yandexbot 1;
    ~*pinterest 1;
    ~*vkshare 1;
    ~*snapchat 1;
}
